### PR TITLE
add support for Oracle database to database driver

### PR DESCRIPTION
**Pull request by IwfY**
* table and column identifiers have to be upper case

### CODE REVIEW

**Comment by edrush** [comment]
Thank you!

Didn't test it but code looks fine.

**Comment by IwfY** [comment]
Good. Please don't forward this change to upstream yet. First your functionality should be merged.
On my fork I created a _feature/oracle-support_ branch for this explicitly.

**Comment by edrush** [comment]
Ups. That just happened automatically...maybe because your PR came from your branch "IwfY:feature/schedule-lock"?

**Comment by edrush** [comment]
Since @spike31 does not want to [merge](https://github.com/lexik/LexikMaintenanceBundle/pull/82) this feature I leave this as is, for now.

**Pull request merged**
